default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: auditOrve_development

  audit:
    <<: *default
    database: auditdb_local
    username: dev_master
    database_tasks: false
    schema_dump: false

test:
  primary:
    <<: *default
    database: audit_orve_test

  audit:
    <<: *default
    database: <%= ENV.fetch("AUDIT_TEST_DATABASE", "auditdb_local") %>
    username: dev_master
    database_tasks: false
    schema_dump: false

production:
  primary:
    <<: *default
    url: <%= ENV["PRIMARY_DATABASE_URL"] %>

  cache:
    <<: *default
    url: <%= ENV["CACHE_DATABASE_URL"] %>
    migrations_paths: db/cache_migrate

  queue:
    <<: *default
    url: <%= ENV["QUEUE_DATABASE_URL"] %>
    migrations_paths: db/queue_migrate

  cable:
    <<: *default
    url: <%= ENV["CABLE_DATABASE_URL"] %>
    migrations_paths: db/cable_migrate

  audit:
    <<: *default
    url: <%= ENV["AUDIT_DATABASE_URL"] %>
    database_tasks: false
    schema_dump: false