default: &default
  adapter: postgresql
  encoding: unicode
  max_connections: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: auditOrve_development

  audit:
    <<: *default
    database: auditdb_local
    username: dev_master
    database_tasks: false
    schema_dump: false

test:
  primary:
    <<: *default
    database: audit_orve_test

  audit:
    <<: *default
    database: <%= ENV.fetch("AUDIT_TEST_DATABASE", "auditdb_local") %>
    username: dev_master
    database_tasks: false
    schema_dump: false

production:
  primary: &primary_production
    <<: *default
    host: <%= ENV["DB_HOST"] %>
    port: <%= ENV.fetch("DB_PORT", 5432) %>
    username: <%= ENV["DB_USERNAME"] %>
    password: <%= ENV["DB_PASSWORD"] %>
    database: <%= ENV.fetch("PRIMARY_DATABASE_NAME", "audit_orve_production") %>

  cache:
    <<: *primary_production
    database: <%= ENV.fetch("CACHE_DATABASE_NAME", "audit_orve_production_cache") %>
    migrations_paths: db/cache_migrate

  queue:
    <<: *primary_production
    database: <%= ENV.fetch("QUEUE_DATABASE_NAME", "audit_orve_production_queue") %>
    migrations_paths: db/queue_migrate

  cable:
    <<: *primary_production
    database: <%= ENV.fetch("CABLE_DATABASE_NAME", "audit_orve_production_cable") %>
    migrations_paths: db/cable_migrate

  audit:
    <<: *default
    host: <%= ENV["DB_HOST"] %>
    port: <%= ENV.fetch("DB_PORT", 5432) %>
    username: <%= ENV["DB_USERNAME"] %>
    password: <%= ENV["DB_PASSWORD"] %>
    database: <%= ENV.fetch("AUDIT_DATABASE_NAME", "auditpr-2026") %>
    database_tasks: false
    schema_dump: false